<a href="https://colab.research.google.com/github/Johannmbo/Pandas/blob/main/Untitled15.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
# Импортируем библиотеку pandas для работы с таблицами (DataFrame)
import pandas as pd

# Чтение CSV-файла с данными по пролонгациям
# df — DataFrame, содержащий информацию о коэффициентах пролонгации по месяцам и менеджерам
df = pd.read_csv('prolongations.csv')
df.head()

    id        month                             AM
0   42  ноябрь 2022   Васильев Артем Александрович
1  453  ноябрь 2022   Васильев Артем Александрович
2  548  ноябрь 2022      Михайлов Андрей Сергеевич
3   87  ноябрь 2022  Соколова Анастасия Викторовна
4  429  ноябрь 2022  Соколова Анастасия Викторовна

In [13]:
# Чтение CSV-файла с финансовыми данными
# # df2 — DataFrame, содержащий финансовую информацию по менеджерам, возможно продажи, выручка и т.д.
df2 = pd.read_csv('financial_data.csv')
df2.head()

,id,Причина дубля,Ноябрь 2022,Декабрь 2022,Январь 2023,Февраль 2023,Март 2023,Апрель 2023,Май 2023,Июнь 2023,Июль 2023,Август 2023,Сентябрь 2023,Октябрь 2023,Ноябрь 2023,Декабрь 2023,Январь 2024,Февраль 2024,Account
0,42,NaN,"36 220,00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Васильев Артем Александрович
1,657,первая часть оплаты,стоп,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Васильев Артем Александрович
2,657,вторая часть оплаты,стоп,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Васильев Артем Александрович
3,594,NaN,стоп,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Васильев Артем Александрович
4,665,NaN,"10 000,00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Васильев Артем Александрович

In [15]:
# Объединяем два DataFrame по общему столбцу 'id'
merge_df = pd.merge(df, df2, on='id')
merge_df.head()

,id,month,AM,Причина дубля,Ноябрь 2022,Декабрь 2022,Январь 2023,Февраль 2023,Март 2023,Апрель 2023,...,Июнь 2023,Июль 2023,Август 2023,Сентябрь 2023,Октябрь 2023,Ноябрь 2023,Декабрь 2023,Январь 2024,Февраль 2024,Account
0,42,ноябрь 2022,Васильев Артем Александрович,NaN,"36 220,00",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Васильев Артем Александрович
1,453,ноябрь 2022,Васильев Артем Александрович,NaN,в ноль,"39 245,00","44 320,00","177 635,00",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Васильев Артем Александрович
2,548,ноябрь 2022,Михайлов Андрей Сергеевич,NaN,"674 000,00","674 000,00","674 000,00","674 000,00",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Михайлов Андрей Сергеевич
3,87,ноябрь 2022,Соколова Анастасия Викторовна,основные работы,"70 050,00",NaN,"73 380,00","83 480,00","89 300,00","89 300,00",...,"72 485,00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Иванова Мария Сергеевна
4,429,ноябрь 2022,Соколова Анастасия Викторовна,NaN,"30 280,00","35 580,00","35 830,00","42 830,00",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Соколова Анастасия Викторовна

In [16]:
# Создаем новый столбец 'Manager'
# merge_df['AM'] — основной столбец с именем менеджера
# merge_df['Account'] — запасной столбец, если AM пустой (NaN)
# combine_first выбирает значение из 'AM', если оно есть, иначе берёт из 'Account'
merge_df['Manager'] = merge_df['AM'].combine_first(merge_df['Account'])
merge_df.head()

,id,month,AM,Причина дубля,Ноябрь 2022,Декабрь 2022,Январь 2023,Февраль 2023,Март 2023,Апрель 2023,...,Июль 2023,Август 2023,Сентябрь 2023,Октябрь 2023,Ноябрь 2023,Декабрь 2023,Январь 2024,Февраль 2024,Account,Manager
0,42,ноябрь 2022,Васильев Артем Александрович,NaN,"36 220,00",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Васильев Артем Александрович,Васильев Артем Александрович
1,453,ноябрь 2022,Васильев Артем Александрович,NaN,в ноль,"39 245,00","44 320,00","177 635,00",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Васильев Артем Александрович,Васильев Артем Александрович
2,548,ноябрь 2022,Михайлов Андрей Сергеевич,NaN,"674 000,00","674 000,00","674 000,00","674 000,00",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Михайлов Андрей Сергеевич,Михайлов Андрей Сергеевич
3,87,ноябрь 2022,Соколова Анастасия Викторовна,основные работы,"70 050,00",NaN,"73 380,00","83 480,00","89 300,00","89 300,00",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Иванова Мария Сергеевна,Соколова Анастасия Викторовна
4,429,ноябрь 2022,Соколова Анастасия Викторовна,NaN,"30 280,00","35 580,00","35 830,00","42 830,00",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Соколова Анастасия Викторовна,Соколова Анастасия Викторовна

In [17]:
# Удаляем ненужные столбцы 'AM' и 'Account'
# # axis=1 указывает, что удаляем столбцы
merge_df = merge_df.drop(['AM', 'Account'], axis=1)
merge_df.head()

,id,month,Причина дубля,Ноябрь 2022,Декабрь 2022,Январь 2023,Февраль 2023,Март 2023,Апрель 2023,Май 2023,Июнь 2023,Июль 2023,Август 2023,Сентябрь 2023,Октябрь 2023,Ноябрь 2023,Декабрь 2023,Январь 2024,Февраль 2024,Manager
0,42,ноябрь 2022,NaN,"36 220,00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Васильев Артем Александрович
1,453,ноябрь 2022,NaN,в ноль,"39 245,00","44 320,00","177 635,00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Васильев Артем Александрович
2,548,ноябрь 2022,NaN,"674 000,00","674 000,00","674 000,00","674 000,00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Михайлов Андрей Сергеевич
3,87,ноябрь 2022,основные работы,"70 050,00",NaN,"73 380,00","83 480,00","89 300,00","89 300,00","78 605,00","72 485,00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Соколова Анастасия Викторовна
4,429,ноябрь 2022,NaN,"30 280,00","35 580,00","35 830,00","42 830,00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Соколова Анастасия Викторовна

In [18]:
# Приводим значения в столбце 'month' к правильному формату заглавных букв
merge_df['month'] = merge_df['month'].str.title()

# Создаём список всех месяцев, которые есть в данных
all_months = list(merge_df.columns[3:-1])

# Проверка наличия всех ожидаемых месяцев в DataFrame
# Если столбец с каким-то месяцем отсутствует, выводим предупреждение
for month in all_months:
    if month not in merge_df.columns:
        print(f"Столбец '{month}' отсутствует!")

# Функция для проверки, был ли проект остановлен ('стоп' или 'end') до или в последнем месяце реализации
def is_project_stopped(row):
    last_month = row['month']  # Определяем последний месяц реализации проекта/идентификатора
    last_month_index = all_months.index(last_month)  # Находим индекс этого месяца в списке всех месяцев
    months_to_check = all_months[:last_month_index+1]  # Берём все месяцы до и включая последний месяц реализации
    # Проверяем, встречается ли в этих месяцах отметка 'стоп' или 'end'
    for month in months_to_check:
        if row[month] in ['стоп', 'end']:
            return True  # Если проект остановлен, возвращаем True
    return False  # Иначе проект активен

# Применяем функцию ко всем строкам merge_df и исключаем строки с остановленными проектами
# ~ означает отрицание, т.е. выбираем только те строки, где проект не остановлен
df_cleaned = merge_df[~merge_df.apply(is_project_stopped, axis=1)]

df_cleaned.head(20)

,id,month,Причина дубля,Ноябрь 2022,Декабрь 2022,Январь 2023,Февраль 2023,Март 2023,Апрель 2023,Май 2023,Июнь 2023,Июль 2023,Август 2023,Сентябрь 2023,Октябрь 2023,Ноябрь 2023,Декабрь 2023,Январь 2024,Февраль 2024,Manager
0,42,Ноябрь 2022,NaN,"36 220,00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Васильев Артем Александрович
1,453,Ноябрь 2022,NaN,в ноль,"39 245,00","44 320,00","177 635,00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Васильев Артем Александрович
2,548,Ноябрь 2022,NaN,"674 000,00","674 000,00","674 000,00","674 000,00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Михайлов Андрей Сергеевич
3,87,Ноябрь 2022,основные работы,"70 050,00",NaN,"73 380,00","83 480,00","89 300,00","89 300,00","78 605,00","72 485,00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Соколова Анастасия Викторовна
4,429,Ноябрь 2022,NaN,"30 280,00","35 580,00","35 830,00","42 830,00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Соколова Анастасия Викторовна
5,600,Ноябрь 2022,первая часть оплаты,"237 977,00","144 650,00","144 650,00","144 650,00","118 300,00","186 395,00","168 820,00","185 370,00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Васильев Артем Александрович
6,600,Ноябрь 2022,вторая часть оплаты,"43 440,00","30 450,00","122 570,00","114 283,00","106 037,00","46 410,00","44 379,00","72 430,00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Васильев Артем Александрович
10,665,Ноябрь 2022,NaN,"10 000,00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Васильев Артем Александрович
11,586,Ноябрь 2022,NaN,"52 240,00",NaN,NaN,"39 660,00","43 240,00","44 880,00","41 005,00","32 940,00","77 330,00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Иванова Мария Сергеевна
12,637,Ноябрь 2022,NaN,"38 045,00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Соколова Анастасия Викторовна
13,419,Ноябрь 2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Михайлов Андрей Сергеевич
14,578,Ноябрь 2022,NaN,"82 800,00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Попова Екатерина Николаевна
15,579,Ноябрь 2022,NaN,в ноль,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Васильев Артем Александрович
16,671,Ноябрь 2022,первая часть оплаты,"28 000,00","37 000,00","37 000,00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Соколова Анастасия Викторовна
17,671,Ноябрь 2022,вторая часть оплаты,NaN,"68 805,00","67 835,00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Соколова Анастасия Викторовна
18,671,Ноябрь 2022,вторая часть оплаты,NaN,NaN,"3 395,00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Соколова Анастасия Викторовна
19,633,Ноябрь 2022,NaN,"40 200,00","40 200,00","40 200,00","40 200,00",NaN,"40 200,00","40 200,00","166 465,00","166 500,00","166 500,00",NaN,NaN,NaN,NaN,NaN,NaN,Васильев Артем Александрович
20,645,Ноябрь 2022,NaN,"58 060,00","46 135,00",NaN,"36 590,00","38 000,00","36 010,00","41 225,00","37 690,00","42 755,00","43 045,00","38 000,00","16 300,00","15 350,00","16 300,00",NaN,NaN,Соколова Анастасия Викторовна
21,369,Ноябрь 2022,основные работы,"42 600,00","7 450,00",NaN,NaN,NaN,NaN,NaN,NaN,"120 190,00","9 460,00","14 190,00","124 920,00",стоп,NaN,NaN,NaN,Васильев Артем Александрович
22,369,Ноябрь 2022,доп работы,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"5 000,00",NaN,NaN,NaN,NaN,NaN,Васильев Артем Александрович

In [19]:
# Смотрим тип данных
df_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
Index: 664 entries, 0 to 724
Data columns (total 20 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             664 non-null    int64
 1   month          664 non-null    object
 2   Причина дубля  480 non-null    object
 3   Ноябрь 2022    236 non-null    object
 4   Декабрь 2022   260 non-null    object
 5   Январь 2023    260 non-null    object
 6   Февраль 2023   291 non-null    object
 7   Март 2023      321 non-null    object
 8   Апрель 2023    334 non-null    object
 9   Май 2023       351 non-null    object
 10  Июнь 2023      343 non-null    object
 11  Июль 2023      327 non-null    object
 12  Август 2023    347 non-null    object
 13  Сентябрь 2023  311 non-null    object
 14  Октябрь 2023   305 non-null    object
 15  Ноябрь 2023    299 non-null    object
 16  Декабрь 2023   261 non-null    object
 17  Январь 2024    174 non-null    object
 18  Февраль 2024   175 non-null    object
 19  Manager        664 non-null    object
dtypes: int64(1), object(19)
memory usage: 108.9+ KB

In [20]:
# Функция для очистки и преобразования значений в числовой формат
def clean_column(col):
    # Если значение в ячейке текстовое
    if isinstance(col, str):
        # Убираем лишние символы: неразрывные пробелы (\xa0), обычные пробелы, заменяем запятую на точку
        col = col.replace('\xa0', '').replace(' ', '').replace(',', '.')
        # Специальные текстовые значения
        if col.lower() == 'вноль':  # если написано 'вноль', присваиваем 0.0
            return 0.0
        elif col in ['стоп', 'end']:  # если проект остановлен, возвращаем None (чтобы пропуск учесть как NaN)
            return None
        else:
            return float(col)  # преобразуем текстовое число в float
    return col  # если значение уже число, оставляем без изменений

# Выбираем диапазон столбцов с месяцами (с 4-го до предпоследнего)
months = df_cleaned.columns[3:-1]

# Применяем функцию очистки ко всем ячейкам по каждому месяцу
for i in months:
    df_cleaned[i] = df_cleaned[i].apply(clean_column)

# Проверяем информацию о DataFrame после преобразования: типы данных, количество непустых значений
df_cleaned.info()

df_cleaned.head(20)

<class 'pandas.core.frame.DataFrame'>
Index: 664 entries, 0 to 724
Data columns (total 20 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             664 non-null    int64
 1   month          664 non-null    object
 2   Причина дубля  480 non-null    object
 3   Ноябрь 2022    236 non-null    float64
 4   Декабрь 2022   260 non-null    float64
 5   Январь 2023    260 non-null    float64
 6   Февраль 2023   291 non-null    float64
 7   Март 2023      321 non-null    float64
 8   Апрель 2023    331 non-null    float64
 9   Май 2023       350 non-null    float64
 10  Июнь 2023      338 non-null    float64
 11  Июль 2023      327 non-null    float64
 12  Август 2023    345 non-null    float64
 13  Сентябрь 2023  311 non-null    float64
 14  Октябрь 2023   305 non-null    float64
 15  Ноябрь 2023    278 non-null    float64
 16  Декабрь 2023   261 non-null    float64
 17  Январь 2024    166 non-null    float64
 18  Февраль 2024   171 non-null    float64
 19  Manager        664 non-null    object
dtypes: float64(16), int64(1), object(3)
memory usage: 108.9+ KB

/tmp/ipython-input-3561734984.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned[i] = df_cleaned[i].apply(clean_column)

,id,month,Причина дубля,Ноябрь 2022,Декабрь 2022,Январь 2023,Февраль 2023,Март 2023,Апрель 2023,Май 2023,Июнь 2023,Июль 2023,Август 2023,Сентябрь 2023,Октябрь 2023,Ноябрь 2023,Декабрь 2023,Январь 2024,Февраль 2024,Manager
0,42,Ноябрь 2022,NaN,36220.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Васильев Артем Александрович
1,453,Ноябрь 2022,NaN,0.0,39245.0,44320.0,177635.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Васильев Артем Александрович
2,548,Ноябрь 2022,NaN,674000.0,674000.0,674000.0,674000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Михайлов Андрей Сергеевич
3,87,Ноябрь 2022,основные работы,70050.0,NaN,73380.0,83480.0,89300.0,89300.0,78605.0,72485.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Соколова Анастасия Викторовна
4,429,Ноябрь 2022,NaN,30280.0,35580.0,35830.0,42830.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Соколова Анастасия Викторовна
5,600,Ноябрь 2022,первая часть оплаты,237977.0,144650.0,144650.0,144650.0,118300.0,186395.0,168820.0,185370.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Васильев Артем Александрович
6,600,Ноябрь 2022,вторая часть оплаты,43440.0,30450.0,122570.0,114283.0,106037.0,46410.0,44379.0,72430.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Васильев Артем Александрович
10,665,Ноябрь 2022,NaN,10000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Васильев Артем Александрович
11,586,Ноябрь 2022,NaN,52240.0,NaN,NaN,39660.0,43240.0,44880.0,41005.0,32940.0,77330.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Иванова Мария Сергеевна
12,637,Ноябрь 2022,NaN,38045.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Соколова Анастасия Викторовна
13,419,Ноябрь 2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Михайлов Андрей Сергеевич
14,578,Ноябрь 2022,NaN,82800.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Попова Екатерина Николаевна
15,579,Ноябрь 2022,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Васильев Артем Александрович
16,671,Ноябрь 2022,первая часть оплаты,28000.0,37000.0,37000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Соколова Анастасия Викторовна
17,671,Ноябрь 2022,вторая часть оплаты,NaN,68805.0,67835.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Соколова Анастасия Викторовна
18,671,Ноябрь 2022,вторая часть оплаты,NaN,NaN,3395.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Соколова Анастасия Викторовна
19,633,Ноябрь 2022,NaN,40200.0,40200.0,40200.0,40200.0,NaN,40200.0,40200.0,166465.0,166500.0,166500.0,NaN,NaN,NaN,NaN,NaN,NaN,Васильев Артем Александрович
20,645,Ноябрь 2022,NaN,58060.0,46135.0,NaN,36590.0,38000.0,36010.0,41225.0,37690.0,42755.0,43045.0,38000.0,16300.0,15350.0,16300.0,NaN,NaN,Соколова Анастасия Викторовна
21,369,Ноябрь 2022,основные работы,42600.0,7450.0,NaN,NaN,NaN,NaN,NaN,NaN,120190.0,9460.0,14190.0,124920.0,NaN,NaN,NaN,NaN,Васильев Артем Александрович
22,369,Ноябрь 2022,доп работы,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5000.0,NaN,NaN,NaN,NaN,NaN,Васильев Артем Александрович

In [21]:
# Убираем Причину дубля
df_agg = df_cleaned.drop(columns=['Причина дубля'])
df_agg.head()

,id,month,Ноябрь 2022,Декабрь 2022,Январь 2023,Февраль 2023,Март 2023,Апрель 2023,Май 2023,Июнь 2023,Июль 2023,Август 2023,Сентябрь 2023,Октябрь 2023,Ноябрь 2023,Декабрь 2023,Январь 2024,Февраль 2024,Manager
0,42,Ноябрь 2022,36220.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Васильев Артем Александрович
1,453,Ноябрь 2022,0.0,39245.0,44320.0,177635.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Васильев Артем Александрович
2,548,Ноябрь 2022,674000.0,674000.0,674000.0,674000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Михайлов Андрей Сергеевич
3,87,Ноябрь 2022,70050.0,NaN,73380.0,83480.0,89300.0,89300.0,78605.0,72485.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Соколова Анастасия Викторовна
4,429,Ноябрь 2022,30280.0,35580.0,35830.0,42830.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Соколова Анастасия Викторовна

In [22]:
# Группируем данные по уникальному идентификатору проекта, месяцу и имени менеджера
# as_index=False — сохраняем группы как обычные столбцы, а не делаем их индексами
# sum(numeric_only=True) — суммируем только числовые столбцы для каждой группы
df_agg = df_agg.groupby(['id', 'month', 'Manager'], as_index=False).sum(numeric_only=True)

In [23]:
# Список месяцев и словарь с индексами для сравнения
months = list(df_agg.columns[3:])
month_ind = {month: i for i, month in enumerate(months)}

# Преобразуем таблицу в длинный формат
df_long = df_agg.melt(id_vars=['id', 'month', 'Manager'], value_vars=months,
                      var_name='Месяц', value_name='Сумма')

# Фильтруем ненулевые и не NaN значения
df_long = df_long[df_long['Сумма'].notna() & (df_long['Сумма'] != 0)]

# Добавляем индексы месяцев для удобства
df_long['index_месяц'] = df_long['Месяц'].map(month_ind)
df_long['index_окончания'] = df_long['month'].map(month_ind)

# Фильтруем строки по условию:
# месяц отгрузки должен быть в пределах месяца окончания и два следующих месяца
df_long['valid'] = df_long.apply(
    lambda row: row['index_окончания'] <= row['index_месяц'] <= row['index_окончания'] + 2,
    axis=1
)

# Оставляем только те строки, где valid == True
df_long = df_long[df_long['valid']]

# Убираем временную колонку 'valid'
df_long = df_long.drop(columns=['valid'])

# Сортируем так, чтобы при drop_duplicates оставить менеджера с минимальным месяцем окончания (т.е. ближайшим)
df_long = df_long.sort_values(by=['id', 'Месяц', 'index_окончания'], ascending=[True, True, True])

# Оставляем по одному менеджеру на (id, Месяц)
df_clean = df_long.drop_duplicates(subset=['id', 'Месяц'], keep='first')

# Выбираем и переименовываем колонки
df_clean = df_clean[['id', 'Месяц', 'Manager', 'month', 'Сумма']].rename(columns={
    'Manager': 'Менеджер',
    'month': 'Месяц_окончания'
})

# Сортируем для удобного просмотра
df_clean = df_clean.sort_values(by=['Месяц'])

# Проверим для id == 31
print(df_clean[df_clean['Менеджер'] == 'Федорова Марина Васильевна'])
df_clean.head(1000)

       id         Месяц                    Менеджер Месяц_окончания    Сумма
6016  958  Декабрь 2023  Федорова Марина Васильевна    Декабрь 2023  50250.0

,id,Месяц,Менеджер,Месяц_окончания,Сумма
4190,803,Август 2023,Смирнова Ольга Владимировна,Август 2023,121930.00
3917,154,Август 2023,Иванова Мария Сергеевна,Июль 2023,70545.00
4156,781,Август 2023,Михайлов Андрей Сергеевич,Август 2023,333853.75
4246,889,Август 2023,Васильев Артем Александрович,Август 2023,64940.00
3921,180,Август 2023,Попова Екатерина Николаевна,Август 2023,192375.00
...,...,...,...,...,...
6273,722,Январь 2024,Попова Екатерина Николаевна,Декабрь 2023,84700.00
6078,190,Январь 2024,Васильев Артем Александрович,Декабрь 2023,104025.00
6130,448,Январь 2024,Кузнецов Михаил Иванович,Декабрь 2023,87743.00
6261,712,Январь 2024,Смирнова Ольга Владимировна,Ноябрь 2023,40970.00
6286,743,Январь 2024,Смирнова Ольга Владимировна,Декабрь 2023,66800.00

In [24]:
def find_coef_with_year(df_clean):
    result = []
    months = list(df_agg.columns[3:])  # Месяцы отгрузки

    # Проходим по каждому менеджеру
    for manager in df_clean['Менеджер'].unique():
        df_manager = df_clean[df_clean['Менеджер'] == manager]

        # Итоговые значения для годовых коэффициентов
        weighted_coef_1_sum, weighted_coef_2_sum, total_shipment_sum = 0, 0, 0

        # Проходим по каждому месяцу окончания
        for month_end in df_manager['Месяц_окончания'].unique():
            # Проекты, завершившиеся в month_end
            projects_end_month = df_manager[df_manager['Месяц_окончания'] == month_end]
            total_end_month = projects_end_month['Сумма'].sum()  # Сумма всех отгрузок в завершённом месяце

            # Индекс месяца окончания
            if month_end not in months:
                print(f"Месяц окончания '{month_end}' не найден в списке месяцев отгрузки")
                continue

            month_index = months.index(month_end)
            next_month = months[month_index + 1] if month_index + 1 < len(months) else None
            second_month = months[month_index + 2] if month_index + 2 < len(months) else None

            # Коэффициент 1: Пролонгации в следующий месяц
            if next_month:
                extended_projects = projects_end_month[projects_end_month['Месяц'] == next_month]
                extended_shipment = extended_projects['Сумма'].sum()
            else:
                extended_shipment = 0

            coef_1 = extended_shipment / total_end_month if total_end_month > 0 else 0

            # Коэффициент 2: Пролонгации во второй месяц
            if second_month:
                non_extended_projects = projects_end_month[
                    (projects_end_month['Месяц'] != next_month) &
                    (projects_end_month['Месяц_окончания'] == month_end)
                ]
                second_extended_projects = non_extended_projects[non_extended_projects['Месяц'] == second_month]
                second_extended_shipment = second_extended_projects['Сумма'].sum()
            else:
                second_extended_shipment = 0

            coef_2 = second_extended_shipment / total_end_month if total_end_month > 0 else 0

            # Обновляем итоговые суммы для расчёта средневзвешенных коэффициентов
            weighted_coef_1_sum += coef_1 * total_end_month
            weighted_coef_2_sum += coef_2 * total_end_month
            total_shipment_sum += total_end_month

            # Добавляем строку для месяца
            result.append({
                'Менеджер': manager,
                'Месяц_окончания': month_end,
                'Коэффициент_1': coef_1,
                'Коэффициент_2': coef_2
            })

        # После прохода по всем месяцам для данного менеджера вычисляем годовой коэффициент
        if total_shipment_sum > 0:
            coef_1_year = weighted_coef_1_sum / total_shipment_sum
            coef_2_year = weighted_coef_2_sum / total_shipment_sum
        else:
            coef_1_year, coef_2_year = 0, 0

        # Добавляем строку с годовыми коэффициентами для менеджера
        result.append({
            'Менеджер': manager,
            'Месяц_окончания': 'Итого за год',
            'Коэффициент_1': coef_1_year,
            'Коэффициент_2': coef_2_year
        })

    # Создаём итоговый DataFrame
    return pd.DataFrame(result)

# Пример использования функции
coef_df = find_coef_with_year(df_clean)

# Печать первых 30 строк
print(coef_df.head(30))

# Печать коэффициентов для конкретного менеджера
print(coef_df[coef_df['Менеджер'] == 'Федорова Марина Васильевна'])

                       Менеджер Месяц_окончания  Коэффициент_1  Коэффициент_2
0   Смирнова Ольга Владимировна     Август 2023       0.258792       0.317534
1   Смирнова Ольга Владимировна       Июль 2023       0.201054       0.259245
2   Смирнова Ольга Владимировна       Июнь 2023       0.000000       0.608314
3   Смирнова Ольга Владимировна       Март 2023       0.321775       0.345160
4   Смирнова Ольга Владимировна    Декабрь 2022       0.300439       0.295417
5   Смирнова Ольга Владимировна    Октябрь 2023       0.326421       0.283234
6   Смирнова Ольга Владимировна    Декабрь 2023       0.213199       0.282658
7   Смирнова Ольга Владимировна     Ноябрь 2023       0.147460       0.286501
8   Смирнова Ольга Владимировна        Май 2023       0.000000       0.340491
9   Смирнова Ольга Владимировна     Январь 2023       0.000000       0.534996
10  Смирнова Ольга Владимировна   Сентябрь 2023       0.342203       0.343156
11  Смирнова Ольга Владимировна    Итого за год       0.257209       0.312966
12      Иванова Мария Сергеевна       Июль 2023       0.280326       0.201200
13      Иванова Мария Сергеевна     Август 2023       0.333172       0.333172
14      Иванова Мария Сергеевна       Июнь 2023       0.272157       0.291009
15      Иванова Мария Сергеевна    Февраль 2023       0.278510       0.375642
16      Иванова Мария Сергеевна       Март 2023       0.084601       0.239697
17      Иванова Мария Сергеевна    Декабрь 2022       0.182934       0.139698
18      Иванова Мария Сергеевна     Апрель 2023       0.000000       1.000000
19      Иванова Мария Сергеевна        Май 2023       0.000000       0.000000
20      Иванова Мария Сергеевна     Ноябрь 2022       0.000000       0.000000
21      Иванова Мария Сергеевна    Итого за год       0.191492       0.208694
22    Михайлов Андрей Сергеевич     Август 2023       0.000000       0.000000
23    Михайлов Андрей Сергеевич     Апрель 2023       0.370031       0.318919
24    Михайлов Андрей Сергеевич    Февраль 2023       0.549049       0.225058
25    Михайлов Андрей Сергеевич       Март 2023       0.333908       0.362218
26    Михайлов Андрей Сергеевич     Ноябрь 2022       0.306766       0.354736
27    Михайлов Андрей Сергеевич    Декабрь 2022       0.283584       0.304184
28    Михайлов Андрей Сергеевич    Декабрь 2023       0.000000       0.508026
29    Михайлов Андрей Сергеевич       Июнь 2023       0.544943       0.000000
                      Менеджер Месяц_окончания  Коэффициент_1  Коэффициент_2
89  Федорова Марина Васильевна    Декабрь 2023            0.0            0.0
90  Федорова Марина Васильевна    Итого за год            0.0            0.0

In [26]:
def find_coef_department(df_clean):
    result = []

    # Получаем список месяцев отгрузки
    months = list(df_agg.columns[3:])

    # Итоговые коэффициенты для всего отдела
    weighted_coef_1_sum, weighted_coef_2_sum, total_shipment_sum = 0, 0, 0

    # Проходим по каждому месяцу окончания
    for month_end in df_clean['Месяц_окончания'].unique():
        # Фильтруем все проекты, завершившиеся в month_end
        projects_end_month = df_clean[df_clean['Месяц_окончания'] == month_end]
        total_end_month = projects_end_month['Сумма'].sum()  # Сумма отгрузок в завершённом месяце

        # Проверка на наличие месяца окончания в списке месяцев отгрузки
        if month_end not in months:
            print(f"Месяц окончания '{month_end}' не найден в списке месяцев отгрузки")
            continue

        month_index = months.index(month_end)
        next_month = months[month_index + 1] if month_index + 1 < len(months) else None
        second_month = months[month_index + 2] if month_index + 2 < len(months) else None

        # Коэффициент 1: Пролонгации в следующий месяц
        if next_month:
            extended_projects = projects_end_month[projects_end_month['Месяц'] == next_month]
            extended_shipment = extended_projects['Сумма'].sum()
        else:
            extended_shipment = 0

        coef_1 = extended_shipment / total_end_month if total_end_month > 0 else 0

        # Коэффициент 2: Пролонгации во второй месяц
        if second_month:
            non_extended_projects = projects_end_month[
                (projects_end_month['Месяц'] != next_month) &
                (projects_end_month['Месяц_окончания'] == month_end)
            ]
            second_extended_projects = non_extended_projects[non_extended_projects['Месяц'] == second_month]
            second_extended_shipment = second_extended_projects['Сумма'].sum()
        else:
            second_extended_shipment = 0

        coef_2 = second_extended_shipment / total_end_month if total_end_month > 0 else 0

        # Добавляем данные для каждого месяца
        result.append({
            'Месяц_окончания': month_end,
            'Коэффициент_1_месяц': coef_1,
            'Коэффициент_2_месяц': coef_2
        })

        # Обновляем суммы для расчёта средневзвешенного коэффициента
        weighted_coef_1_sum += coef_1 * total_end_month
        weighted_coef_2_sum += coef_2 * total_end_month
        total_shipment_sum += total_end_month

    # Рассчитываем средневзвешенные коэффициенты для всего отдела за год
    if total_shipment_sum > 0:
        coef_1_year = weighted_coef_1_sum / total_shipment_sum
        coef_2_year = weighted_coef_2_sum / total_shipment_sum
    else:
        coef_1_year, coef_2_year = 0, 0

    # Добавляем строку с итоговыми коэффициентами для всего отдела за год
    result.append({
        'Месяц_окончания': 'Итого за год',
        'Коэффициент_1_месяц': coef_1_year,
        'Коэффициент_2_месяц': coef_2_year
    })

    return pd.DataFrame(result)

# Пример использования функции
department_coef_df = find_coef_department(df_clean)
print(department_coef_df)

   Месяц_окончания  Коэффициент_1_месяц  Коэффициент_2_месяц
0      Август 2023             0.204794             0.233897
1        Июль 2023             0.210427             0.255099
2        Июнь 2023             0.300406             0.277427
3     Февраль 2023             0.276373             0.324916
4        Март 2023             0.226807             0.256020
5      Апрель 2023             0.254763             0.368171
6     Декабрь 2022             0.231127             0.251992
7      Ноябрь 2022             0.271247             0.322851
8     Октябрь 2023             0.263477             0.297130
9     Декабрь 2023             0.236837             0.281623
10     Ноябрь 2023             0.291932             0.301221
11        Май 2023             0.143812             0.205412
12     Январь 2023             0.306155             0.451450
13   Сентябрь 2023             0.316528             0.321104
14    Итого за год             0.254667             0.293666